import fs from 'fs';

console.log("Read all constants from All Constants.4dm");

// Read all constants from All Constants.4dm, split them into an array:
let constants = fs.readFileSync('All Constants.4dm', 'utf8').split('\r\n');


// Create .$Dm to create a string with all constant names and values
let txt = `//%attributes = {}
C_TEXT:C284($allConstants)

$allConstants:="// Generated by allConstantsToJsFile.$dm which is generated by generate4dmConstants.js from all 20.6 constants"+Char:C90(13)
$allConstants:=$allConstants+"// Not all constants will be needed for a server-only project "+Char:C90(13)
$allConstants:=$allConstants+"// Some need escaping or adapting like \\"Folder separator\\" = path.sep "+Char:C90(13)
$allConstants:=$allConstants+"// Constants are now immediatly replaced with their values in JS. Optionally use the actual constants in Javascript (remove spaces from constantnames) and import them where needed. "+Char:C90(13)
$allConstants:=$allConstants+"import path from 'path';"+Char:C90(13)
$allConstants:=$allConstants+"export default {" 
`;

constants.forEach((constantSource) => {

    if ( constantSource === '' || constantSource.startsWith('//') ) {
        return;
    }

    let constantName = constantSource.split(':')[0];
    if ( constantName !== "Folder separator" ) { // FIXME better escape, QnD added below
        txt += `$allConstants:=$allConstants+"\\"${ constantSource }\\": \\""+String:C10(${ constantSource })+"\\","` + '\n'; 
    }
    
});

txt += `
$allConstants:=$allConstants+"\\"Folder separator\\": path.sep,"
$allConstants:=$allConstants+"}"
TEXT TO DOCUMENT("constants.js"; $allConstants)
`; 

console.log("Write allConstantsToJsFile.4dm");
fs.writeFileSync("./allConstantsToJsFile.4dm", txt);